# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Bomberman/Bomberman-Vivado/Bomberman-Vivado.srcs/sources_1/ip/numbers_dm/numbers_dm.xci
# IP: The module: 'numbers_dm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Bomberman/Bomberman-Vivado/Bomberman-Vivado.srcs/sources_1/ip/numbers_dm/numbers_dm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'numbers_dm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Bomberman/Bomberman-Vivado/Bomberman-Vivado.srcs/sources_1/ip/numbers_dm/numbers_dm.xci
# IP: The module: 'numbers_dm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Bomberman/Bomberman-Vivado/Bomberman-Vivado.srcs/sources_1/ip/numbers_dm/numbers_dm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'numbers_dm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
