# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Bomberman/Bomberman-Vivado/Bomberman-Vivado.srcs/sources_1/ip/enemy_sprite_br/enemy_sprite_br.xci
# IP: The module: 'enemy_sprite_br' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Bomberman/Bomberman-Vivado/Bomberman-Vivado.srcs/sources_1/ip/enemy_sprite_br/enemy_sprite_br_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'enemy_sprite_br'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Bomberman/Bomberman-Vivado/Bomberman-Vivado.srcs/sources_1/ip/enemy_sprite_br/enemy_sprite_br.xci
# IP: The module: 'enemy_sprite_br' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Bomberman/Bomberman-Vivado/Bomberman-Vivado.srcs/sources_1/ip/enemy_sprite_br/enemy_sprite_br_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'enemy_sprite_br'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
